services:
  - type: web
    name: notifyhub-backend
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements-prod.txt && python manage.py collectstatic --noinput && python manage.py migrate && python manage.py seed_triggers
    startCommand: gunicorn config.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings
      - key: DEBUG
        value: 'False'
      - key: ALLOWED_HOSTS
        value: '*'
