services:
  - type: web
    name: notification-backend
    runtime: python
    buildCommand: pip install -r requirements-prod.txt && python manage.py collectstatic --noinput && python manage.py migrate && python manage.py seed_triggers

    startCommand: gunicorn config.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: 'False'
      - key: DATABASE_URL
        fromDatabase:
          name: notification-db
          property: connectionString
      - key: ALLOWED_HOSTS
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        sync: false
      - key: WHATSAPP_ACCESS_TOKEN
        sync: false
      - key: PHONE_NUMBER_ID
        sync: false
      - key: BREVO_API_KEY
        sync: false
      - key: BREVO_FROM_EMAIL
        sync: false
      - key: ONESIGNAL_APP_ID
        sync: false
      - key: ONESIGNAL_REST_API_KEY
        sync: false
      - key: FRONTEND_URL
        sync: false

databases:
  - name: notification-db
    plan: free
